version: '3.9'

services:
  # Redis for job queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Document conversion worker
  worker-doc:
    build:
      context: ./workers/doc
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - /tmp:/tmp

  # Image conversion worker
  worker-img:
    build:
      context: ./workers/img
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - /tmp:/tmp

  # Audio/Video conversion worker
  worker-av:
    build:
      context: ./workers/av
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - /tmp:/tmp

  # File cleanup worker
  janitor:
    build:
      context: ./workers/janitor
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - /tmp:/tmp

volumes:
  redis_data:
